# VERSION               0.0.1
#
# docker build -t yuanying/php .

FROM ubuntu
MAINTAINER O. Yuanying "yuan-docker@fraction.jp"

RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
RUN apt-get update
RUN apt-get -y install php5
